# Generated by Django 4.0.3 on 2022-03-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60)),
                ('Course_Number', models.IntegerField(blank=True, null=True)),
                ('Instructor_Name', models.CharField(max_length=60)),
                ('Duration', models.DurationField()),
            ],
        ),
    ]
